---
- name: set root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: restart mysql
  service: name=mysql state=restarted
