---
- name: Configuring app servers
  hosts: appservers
  sudo: yes

  vars:
    php_fpm_apt_packages:
      - php5-fpm
      - php5-cli 
      - php5-apcu
      - php5-mysql
      - php5-intl
      - php5-curl
      - php5-imagick

    php_fpm_pools:
      - name: achmed
        user: achmed
        group: achmed
        listen: /var/run/php5-fpm-achmed.sock
        listen.owner: www-data
        listen.group: www-data
        listen.mode: "0660"

    php_fpm_ini:
      # PHP section directives
      - option: "error_reporting"
        section: "PHP"
        value: "E_ALL"
      - option: "display_errors"
        section: "PHP"
        value: "Off"
      - option: "display_startup_errors"
        section: "PHP"
        value: "Off"
      - option: "log_errors"
        section: "PHP"
        value: "On"
      - option: "date.timezone"
        section: "PHP"
        value: "UTC"

    nginx_ubuntu_pkg:
      - nginx

    nginx_sites:
      achmed-master:
         - listen 80
         - server_name {{ inventory_hostname }}
         - root /home/achmed/master/current/web
         - access_log /var/log/nginx/{{ inventory_hostname }}.access_log
         - error_log /var/log/nginx/{{ inventory_hostname }}.error_log
         - "location / { try_files $uri /app.php$is_args$args; }"
         -  location ~ ^/(app)\.php(/|$) {
            fastcgi_pass unix:/var/run/php5-fpm-achmed.sock;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTPS off;
            internal;
          }
      achmed-wildcard:
         - listen 80
         - "server_name ~^(?<subdomain>.*).{{ inventory_hostname }}$"
         - root /home/achmed/$subdomain/current/web
         - access_log /var/log/nginx/wildcard.{{ inventory_hostname }}.access_log
         - error_log /var/log/nginx/wildcard.{{ inventory_hostname }}.error_log
         - "location / { try_files $uri /app.php$is_args$args; }"
         - location ~ ^/(app)\.php(/|$) {
            fastcgi_pass unix:/var/run/php5-fpm-achmed.sock;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTPS off;
            internal;
          }

  roles: [nbz4live.php-fpm, jdauphant.nginx]

  pre_tasks:
    - name: Allow all access to tcp port 80
      ufw: rule=allow port=80 proto=tcp

    - name: Create application user
      user:
        name:  achmed
        shell: /bin/bash

  post_tasks:
    # https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1272788
    - name: Fix service php5-fpm reload
      lineinfile:
        dest: /etc/init/php5-fpm.conf
        state: present
        regexp: '^reload'
        line: "reload signal USR2"
        insertafter: "^# reload"
