---
- name: Build the package
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
    build_dir: "{{ project_source_path }}/build"
    build_name: "{{ version }}"
  tasks:
    - name: Check if bower.json exists
      stat:
        path: "{{ project_source_path }}/bower.json"
      register: bower_json

    - name: Run bower install
      command: >
        bower install --production --silent
      args:
        chdir: "{{ project_source_path }}"
        creates: "{{ project_source_path }}/bower_components"
      when: bower_json.stat.exists == true
      notify:
        - create archive

    - name: Install composer
      get_url: 
        url: https://getcomposer.org/composer.phar
        dest: "{{ project_source_path }}/composer.phar"
        mode: 0755
        validate_certs: no

    - name: Run composer install
      command: >
        "php {{ project_source_path}}/composer.phar install 
        --no-dev  --ignore-platform-reqs --no-interaction
        --prefer-dist --optimize-autoloader --quiet"
      args:
        chdir: "{{ project_source_path }}"
        creates: "{{ project_source_path }}/vendor"
      environment:
        SYMFONY_ENV: prod
      notify:
        - create archive

    - name: set archive path
      set_fact:
        build_archive_path: "{{ build_dir }}/{{ build_name }}.tar.bz2"

    - name: Dump build archive path
      debug: var=build_archive_path

  handlers:
    - name: create archive
      command: >
        tar -jcf {{ build_archive_path }} -C {{ project_source_path }}
        --exclude='build/*'
        --exclude='.git/*'
        --exclude='.vagrant/*'
        --exclude='Vagrantfile'
        --exclude='provisioning/*'
        --exclude='bin/*'
        --exclude='web/uploads/*'
        --exclude='app/logs/*'
        .
