---
- name: Common configuration for all servers
  hosts: all:!devservers
  sudo: yes

  tasks:
    - name: disable ipv6
      sysctl: name={{ item }} value=1 state=present
      with_items:
       - net.ipv6.conf.all.disable_ipv6
       - net.ipv6.conf.default.disable_ipv6
       - net.ipv6.conf.lo.disable_ipv6

    - name: Allow OpenSSH
      ufw: rule=allow name=OpenSSH

    - name: Enable UFW
      ufw: state=enabled policy=deny
