---
- name: Configure db servers
  hosts: dbservers
  sudo: yes

  vars:
    mysql_root_password: mysql_root_pass
    mysql_databases:
      - { name: achmed }
    mysql_users:
      - { name: achmed, password: achmed, database: achmed }
    mysql_server_config:
      performance_schema: "off"

  roles:
    - percona-mysql
