---
- name: Deploy a release
  hosts: appservers
  remote_user: achmed

  vars:
    project_root: "/home/achmed/master/"
    project_deploy_strategy: git
    project_git_repo: git@github.com:dincho/achmed.git
    project_has_composer: true
    project_has_bower: true
    project_composer_binary: composer
    project_command_for_composer_install: >
      {{ project_composer_binary }} install --no-ansi --no-dev --no-interaction 
      --no-progress --optimize-autoloader --no-scripts --prefer-dist

    project_templates:
      - src: "{{ project_parameters_template | default('templates/parameters.j2') }}"
        dest: app/config/parameters.yml

    project_environment:
      SYMFONY_ENV: "prod"

    project_shared_children:
      - path: "/web/uploads"
        src: "uploads"

    project_unwanted_items:
      - .git
      - web/app_dev.php
      - provisioning

    project_post_build_commands:
      - "php vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php"
      - "app/console cache:clear"
      - "app/console doctrine:schema:update --force"
      - "app/console assets:install --relative --symlink"
      - "app/console assetic:dump"

  pre_tasks:
    - name: ensure github.com is a known host
      lineinfile:
        dest: ~/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"

    - name: Get composer github token
      command: "{{ project_composer_binary }} config -g github-oauth.github.com"
      register: github_token_config
      when: github_token is defined

    - name: Set composer github token
      command: "{{ project_composer_binary }} config -g github-oauth.github.com {{ github_token }}"
      when: github_token is defined and github_token_config.stdout == ""

  roles:
       - f500.project_deploy

  post_tasks:
      - name: reload php5-fpm
        service: name=php5-fpm state=reloaded
        remote_user: root

      - name: Remove old releases
        deploy_helper: "path={{ project_root }} state=clean"
