---
- name: Configure dev environment
  hosts: devservers
  sudo: yes
  tasks:
    - name: update apt cache
      apt: update_cache=yes

    - name: php5 is installed
      apt: pkg={{ item }} state=installed
      with_items:
       - php5-fpm
       - php5-cli 
       - php5-apcu
       - php5-mysql
       - php5-intl
       - php5-curl
       - php5-imagick
      notify:
        - restart php-fpm

    - name: install xdebug, nodejs, npm, compass, git
      apt: pkg={{ item }} state=installed
      with_items:
       - php5-xdebug
       - npm
       - nodejs-legacy
       - ruby-compass
       - git
      notify:
        - restart php-fpm

    - name: install bower
      npm: name=bower global=yes state=present

    - name: xdebug module is enabled
      command: php5enmod -s fpm xdebug creates=/etc/php5/fpm/conf.d/20-xdebug.ini
      notify:
        - restart php-fpm

    - name: Create application user
      user: name={{ app_user }}

    - name: Create project dir
      file: 
        path: "{{ project_path }}"
        state: directory
        mode: 0755
        owner: "{{ app_user }}"

    - name: Install asset dependencies
      command: >
        bower install --production --silent
      args:
        chdir: "{{ project_path }}"
        creates: "{{ project_path }}/bower_components"
      sudo: no

    - name: Install composer
      get_url:
        url: https://getcomposer.org/composer.phar
        dest: "{{ project_path }}/composer.phar"
        mode: 0755
        validate_certs: no
        force: no #don't download if already exists
      sudo: no

    - name: Set composer github token
      command: "{{ project_path }}/composer.phar config -g github-oauth.github.com {{ github_token }}"
      sudo: no
      when: github_token is defined

    - name: Install dependencies
      command: >
        {{ project_path }}/composer.phar install --no-interaction
        --prefer-dist --optimize-autoloader
      args:
        chdir: "{{ project_path }}"
        creates: "{{ project_path }}/vendor"
      sudo: no

    - name: Install database
      command: >
        php {{ project_path }}/app/console doctrine:schema:update --force
      sudo: no

  handlers:
    - name: restart php-fpm
      service: name=php5-fpm state=restarted
